/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new game
         * @description Creates a new game and automatically adds the creator as the host
         */
        post: operations["createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{gameUuid}/start/{hostUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a game
         * @description Starts the game, dealing cards and setting up teams. Only the host can start the game.
         */
        post: operations["startGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{gameUuid}/move/{playerUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a player's move
         * @description Applies a move action for the current player and returns the updated game state
         */
        post: operations["doPlayerAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/join/{gameUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join an existing game
         * @description Adds a new player to an existing game that has not yet started
         */
        post: operations["joinGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{gameUuid}/{playerUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game details
         * @description Returns the current state of a game including players, status, and board
         */
        get: operations["getGameDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{gameUuid}/player/{playerUuid}/hand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a player's hand
         * @description Returns the cards in a player's hand. Requires the player's private UUID.
         */
        get: operations["getGamePlayerHand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGameStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlayerNameRequest: {
            playerName?: string;
        };
        GameJoinedResponse: {
            /** Format: uuid */
            gameUuid?: string;
            /** Format: uuid */
            publicPlayerUuid?: string;
            /** Format: uuid */
            privatePlayerUuid?: string;
            playerName?: string;
        };
        BoardResponse: {
            spaces?: components["schemas"]["BoardSpaceResponse"][];
        };
        BoardSpaceResponse: {
            /** Format: int32 */
            row?: number;
            /** Format: int32 */
            col?: number;
            /** @enum {string} */
            colour?: "RED" | "BLUE" | "GREEN";
            card?: components["schemas"]["Card"];
            partOfSequence?: boolean;
        };
        Card: {
            /** @enum {string} */
            suit?: "SPADES" | "HEARTS" | "DIAMONDS" | "CLUBS";
            /** Format: int32 */
            value?: number;
            oneEyedJack?: boolean;
            twoEyedJack?: boolean;
        };
        GameResponse: {
            /** Format: uuid */
            uuid?: string;
            /** Format: int32 */
            maxPlayerSize?: number;
            /** Format: int32 */
            playerCount?: number;
            /** @enum {string} */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            players?: string[];
            playerTeams?: {
                [key: string]: "RED" | "BLUE" | "GREEN";
            };
            playerNames?: {
                [key: string]: string;
            };
            /** Format: uuid */
            host?: string;
            board?: components["schemas"]["BoardResponse"];
            /** Format: uuid */
            currentPlayerTurn?: string;
            playerHand?: components["schemas"]["Card"][];
            /** @enum {string} */
            winner?: "RED" | "BLUE" | "GREEN";
        };
        MoveAction: {
            /** Format: int32 */
            row?: number;
            /** Format: int32 */
            column?: number;
            card?: components["schemas"]["Card"];
        };
        GamePlayerHandResponse: {
            cards?: components["schemas"]["Card"][];
        };
        GameStatsResponse: {
            /** Format: uuid */
            gameUuid?: string;
            /** @enum {string} */
            winner?: "RED" | "BLUE" | "GREEN";
            sequences?: {
                [key: string]: number;
            };
            amountOfTurns?: {
                [key: string]: number;
            };
            chipsPlaced?: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlayerNameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJoinedResponse"];
                };
            };
        };
    };
    startGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameUuid: string;
                hostUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description User is not the host */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Game not found or not full */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    doPlayerAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameUuid: string;
                playerUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveAction"];
            };
        };
        responses: {
            /** @description Move applied successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Invalid player UUID */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Move is not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    joinGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameUuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlayerNameRequest"];
            };
        };
        responses: {
            /** @description Successfully joined the game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJoinedResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJoinedResponse"];
                };
            };
            /** @description Game is already full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJoinedResponse"];
                };
            };
        };
    };
    getGameDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameUuid: string;
                playerUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game details retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    getGamePlayerHand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameUuid: string;
                playerUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player hand retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePlayerHandResponse"];
                };
            };
            /** @description Invalid player UUID */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePlayerHandResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePlayerHandResponse"];
                };
            };
        };
    };
    getGameStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatsResponse"][];
                };
            };
        };
    };
}
